import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="grid grid-cols-2 gap-4 px-4">
          <a href="/" className="text-blue-500 hover:underline">
            HOME
          </a>
          <a href="/collections" className="text-blue-500 hover:underline">
            COLLECTIONS
          </a>
        </div>
        {children}
      </body>
    </html>
  );
}
